services:
  mc:
    image: itzg/minecraft-server
    container_name: volumedata_minecraft_1
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /home/umbrel/umbrel/app-data/volumedata-minecraft:/data
